CREATE TABLE [dbo].[Category]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Name] NVARCHAR(MAX) NOT NULL, 
    [IsDelete] BIT NOT NULL DEFAULT 0, 
    [CreateTime] DATETIME NOT NULL DEFAULT GETDATE(), 
    [UpdateTime] DATETIME NOT NULL DEFAULT GETDATE()
)
