CREATE TABLE [dbo].[OrderHeader]
(
	[Id] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [UserId] NVARCHAR(MAX) NOT NULL, 
    [Status] INT NOT NULL DEFAULT 0, 
    [Remark] NVARCHAR(MAX) NULL, 
    [UpdateTime] DATETIME NOT NULL DEFAULT GETDATE(), 
    [CreateTime] DATETIME NOT NULL DEFAULT GETDATE(), 
    [ShipNumber] NVARCHAR(MAX) NULL, 
    [FailCode] INT NULL DEFAULT 0
)
